### ISSUE TITLE
BAN download not working

### ISSUE THREAD

**Issue by Kanamahk** [DeVilhena-Paulo/Geocoding#6]
Hi,
Running "geocode update" and "geocode download" return a TypeError.
Here is the traceback:

E:\Documents\itineraire etudiant>geocoding download
Traceback (most recent call last):
  File "e:\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "e:\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "E:\Documents\itineraire etudiant\geocodeAdresses\Scripts\geocoding.exe\__main__.py", line 7, in <module>
  File "e:\documents\itineraire etudiant\geocodeadresses\lib\site-packages\geocoding\__main__.py", line 27, in main
    success = function()
  File "e:\documents\itineraire etudiant\geocodeadresses\lib\site-packages\geocoding\download.py", line 46, in get_ban_file
    done, total_size = 0, int(response.headers.get('content-length'))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

It seems that the problem is that the instalation/package does not have the change made to adapt to new BAN database files made last year.

**Comment by DeVilhena-Paulo** [comment]
Hi,

Thanks for that.

Actually, the contributor @chrlryo has already updated the project to work with the new format of the BAN files.

The problem is that I haven't yet released a new version of the package. So if you download it using `pip install geocoding`, you will get the outdated version.

In the meanwhile, if you still want to use Geocoding, you can download the source code from its github page and then run the setup commands by yourself. Here is how you can do it:

First, get a local copy of the project:

`$ git clone https://github.com/DeVilhena-Paulo/Geocoding.git`

Then, move to the project directory:

`$ cd Geocoding`

Next, you will need to launch python (version 3):

`$ python`

Finally, from the python interpreter, you can execute the setup commands (this will take a while):

```
>>> from geocoding.download import get_ban_file, decompress
>>> from geocoding.index import  process_files, create_database
>>> get_ban_file()
>>> decompress()
>>> process_files()
>>> create_database()
```

Once the setup is complete, you can `import geocoding` and use `geocoding.find` as demonstrated in the [README](https://github.com/DeVilhena-Paulo/Geocoding/blob/master/README.rst) file.

**Comment by Kanamahk** [comment]
Hi,
Thank you for the helpfull answer, but I had managed to make it work on my own^^
And thank you also for the very helpfull project^^
